= Kodein DI on Android
Salomon BRYS <salomon.brys@gmail.com>
:toc: left
:toc-position: left
:toclevels: 5

:version: 5.2.0
:branch: 5.2

You can use Kodein as-is in your Android project or use the util library `kodein-android`.

NOTE: Kodein does work on Android as-is.
      The `kodein-android` extension adds multiple android-specific utilities to Kodein. +
      Using or not using this extension really depends on your needs.

Have a look at the https://github.com/Kodein-Framework/Kodein-DI/tree/{branch}/demo/demo-android[Android demo project]!

[[install]]
== Install

.How to use `kodein-android`:
. Add this line in your `dependencies` block in your application `build.gradle` file:
+
[subs="attributes"]
----
compile 'org.kodein.di:kodein-di-generic-jvm:{version}'
compile 'org.kodein.di:kodein-di-framework-android-???:{version}'
----
+
Kodein offers support for:
+
[cols="1,2"]
|=======
| *Android only*               | `kodein-di-framework-android-core`
| *Android + Support library*  | `kodein-di-framework-android-support`
| *Android + AndroidX library* | `kodein-di-framework-android-x`
|=======
+
IMPORTANT: Either `kodein-di-generic-jvm` or `kodein-di-erased-jvm` *must* be declared in addition to the Kodein-Android package. +
+
WARNING: If you are using `SupportFragment` in your application, then you *must* use either the `-support` or the `-x` package.

. Declare the dependency bindings in the Android `Application`, having it implements `KodeinAware`.
+
[source, kotlin]
.Example: an Android Application class that implements KodeinAware
----
class MyApp : Application(), KodeinAware {
	override val kodein = Kodein.lazy { <1>
	    /* bindings */
	}
}
----
<1> Using `Kodein.lazy` allows you to access the `Context` at binding time.
+
TIP: Don't forget to declare the Application in the `AndroidManifest.xml` file!

. In your Activities, Fragments, and other context aware android classes, retrieve the `Kodein` object with the `closestKodein` function.

. Retrieve your dependencies!


== Retrieving

Injection does not work on Android classes that are reified by the system (`Activity`, `Fragment`, etc.) due the fact that... they are reified by the system!
Therefore, on such classes, you need can either use retrieval, or if you want these classes to be independent of Kodein, use the <<dependency-holder,dependency holder pattern>>.


=== Getting a Kodein object

You can always get the `Kodein` object by using:

- `closestKodein()` inside an Android class (such as `Context`, `Activity`, `Fragment`, etc.)
- `closestKodein(context)` or `closestKodein(() -> context)` inside another class

CAUTION: The `closestKodein` function will only work if your Android `Application` class implements the `KodeinAware` interface.

TIP: The `closestKodein` result should be cached and not used multiple times in a row.


=== Being KodeinAware

It is very simple to have your Android classes be `KodeinAware`:

[source, kotlin]
.Example: a KodeinAware Android Activity
----
class MyActivity : Activity(), KodeinAware {
    override val kodein by closestKodein()
    val ds: DataSource by instance()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        ds.connect() <1>
        /* ... */
    }
}
----
<1> Because everything is lazy, the `kodein` AND `ds` instances will both be retrieved only when needed, which is at that time.


=== Using a Trigger

If you want all dependencies to be retrieved at `onCreate`, you can very easily use an trigger:

[source, kotlin]
.Example: using an trigger in a KodeinAware Android Activity
----
class MyActivity : Activity(), KodeinAware {
    override val kodein by closestKodein()
    override val kodeinTrigger = KodeinTrigger()
    val ds: DataSource by instance()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        kodeinTrigger.trigger() <1>
        /* ... */
    }
}
----
<1> The `kodein` AND all dependencies will both be retrieved at that time.

NOTE: Using this approach has an important advantage: as all dependencies are retrieved in `onCreate`, you can be sure that all your dependencies have correctly been retrieved, meaning that there were no non-declared dependency. +
      If you only use `instance` (no `provider` or `factory`), you can also be sure that there were no dependency loop.


== Android module

Kodein-Android proposes a `Module` that enables easy retrieval, of a lot of standard android services.

NOTE: This module is absolutely *optional*, you are free to use it or leave it ;).

[source, kotlin]
.Example: importing the android module
----
class MyApplication : Application(), KodeinAware {
    override val kodein = Kodein.lazy {
        import(androidModule(this@MyApplication))
	    /* bindings */
    }
}
----

You can see everything that this module proposes in the Kodein-Android https://github.com/Kodein-Framework/Kodein-DI/blob/{branch}/framework/kodein-framework-android/src/main/java/org/kodein/android/module.kt[module.kt] file.

[source, kotlin]
.Example: using kodein to retrieve a LayoutInflater
----
class MyActivity : Activity(), KodeinAware {
    override val kodein by closestKodein()
    val inflater: LayoutInflater by instance() <1>
}
----

If you are retrieving these classes inside a non-Android class, you need to define an Android `Context` as a Kodein context:

[source, kotlin]
.Example: using kodein with a context to retrieve a LayoutInflater
----
val inflater: LayoutInflater by kodein.on(context = getActivity()).instance()
----

or

[source, kotlin]
.Example: using kodein with a class context to retrieve a LayoutInflater
----
class MyController(androidContext: Context) : KodeinAware {
    override val kodein by androidContext.closestKodein()
    override val kodeinContext = kcontext(androidContext)
    val inflater: LayoutInflater by instance()
}
----


== Layered dependencies

=== Component based Kodein

In Android, each component has its own lifecycle, much like a "mini application".
You may need to have dependencies that are defined only inside a specific activity.
Kodein allows you to create a `Kodein` instance that lives only inside your own Activity:

[source, kotlin]
.Example: defining an Activity specific Kodein
----
class MyActivity : Activity(), KodeinAware {
    private val _parentKodein by closestKodein() <1>
    override val kodein: Kodein = Kodein {
        extend(_parentKodein) <2>
        /* activity specific bindings */
    }
}
----
<1> Get the "global" application kodein.
<2> Extends the "global" application kodein, to be able to access, with this new `Kodein` object, all bindings defined at the application level.


=== Activity Retained Kodein

Kodein-Android provides `retainedKodein` for Activities.
It creates a Kodein object that is *immune to activity restarts*.

CAUTION: This means that you *should never access the containing activity* it may have been restarted and not valid anymore!

[source, kotlin]
.Example: defining an Activity specific Kodein
----
class MyActivity : Activity(), KodeinAware {
    private val _parentKodein by closestKodein()
    override val kodein: Kodein by retainedKodein { <1>
        extend(_parentKodein)
        /* activity specific bindings */
    }
}
----
<1> Using `retainedKodein` instead of `Kodein` ensures that the Kodein object is retained and not recreated between activity restarts.


=== The Closest Kodein pattern

Android components can be thought as layers.
For example, a `View` defines a layer, on top of an `Activity` layer, itself on top of the `Application` layer.

The `closestKodein` function will always return the kodein of the closest parent layer.
In a `View` or a `Fragment`, for example, it will return the containing Activity's Kodein, if it defines one, else it will return the "global" Application Kodein.

In the previous code example, if `MyActivity` contains Fragments, and that these fragments get their Kodein object via `closestKodein`, they will receive the `MyActivity` Kodein object, instead of the Application one.


== Android scopes

=== Component scopes

Kodein-Android provides a standard scope for any android component:

[source, kotlin]
.Example: using an Activity scope
----
val kodein = Kodein {
    bind<Controller>() with scoped(AndroidComponentsWeakScope<Activity>()).singleton { ControllerImpl(context) } <1>
}
----
<1> `context` is of type `Activity` because we are using the `androidScope<Activity>()`.

CAUTION: This scope is *NOT* compatible with `ScopeCloseable`.


=== Activity retained scope

Kodein-Android provides the `ActivityRetainedScope`, which is a scope that allows activity-scoped singletons or multitons that are independent from the activity restart.

This means that for the same activity, you'll get the same instance, even if the activity restarts.

CAUTION: This means that you *should never retain the activity* passed at creation because it may have been restarted and not valid anymore!

[source, kotlin]
.Example: using an Activity retained scope
----
val kodein = Kodein {
    bind<Controller>() with scoped(ActivityRetainedScope).singleton { ControllerImpl() }
}
----

NOTE: This scope *IS* compatible with `ScopeCloseable`: http://kodein.org/Kodein-DI/?{branch}/core#scope-closeable[see documentation].


=== Lifecycle scope

Kodein-Android provides the `AndroidLifecycleScope`, which is a scope that allows activity-scoped singletons or multitons that are bound to a component lifecycle.
It uses Android support Lifecycle, so you need to use Android support's `LifecycleOwner` components.

Note that these lifecycles

[source, kotlin]
.Example: using an Activity retained scope
----
val kodein = Kodein {
    bind<Controller>() with scoped(AndroidLifecycleScope<Activity>()).singleton { ControllerImpl(context) }
}
----

NOTE: These lifecycles are *NOT* immune to activity restart due to configuration change.

NOTE: This scope *IS* compatible with `ScopeCloseable`: http://kodein.org/Kodein-DI/?{branch}/core#scope-closeable[see documentation].


== Kodein in Android without the extension

=== Being KodeinAware

It is quite easy to have your Android components being KodeinAware (provided that your `Application` class is `KodeinAware`).


==== Using lazy

[source, kotlin]
.Example: a KodeinAware Activity
----
class MyActivity : Activity(), KodeinAware {
    override val kodein: Kodein by lazy { (applicationContext as KodeinAware).kodein }
}
----


==== Using lateinit

[source, kotlin]
.Example: a KodeinAware Activity
----
class MyActivity : Activity(), KodeinAware {
    override lateinit val kodein: Kodein
    override fun onCreate(savedInstanceState: Bundle?) {
        kodein = (applicationContext as KodeinAware).kodein
    }
}
----


=== Using LateInitKodein

If you don't want the component classes to be KodeinAware, you can use a `LateInitKodein`:

[source, kotlin]
.Example: an Activity with LateInitKodein
----
class MyActivity : Activity() {
    val kodein = LateInitKodein()
    override fun onCreate(savedInstanceState: Bundle?) {
        kodein.baseKodein = (applicationContext as KodeinAware).kodein
    }
}
----


[[dependency-holder]]
=== The dependency holder pattern

If you want your components to be Kodein-independent, you can use the dependency holder pattern:

[source, kotlin]
.Example: The dependency holder pattern
----
class MyActivity : Activity() {
    class Deps(
            val ds: DataSource,
            val ctrl: controller
    )
    val deps by lazy { (applicationContext as MyApplication).creator.myActivity() }
    val ds by lazy { deps.ds }
    val ctrl by lazy { deps.ctrl }
    /* ... */
}

class MyApplication : Application() {
	interface Creator {
	    fun myActivity(): MyActivity.Deps
	}
	val creator = KodeinCreator()
        /* ... */
}

class KodeinCreator : MyApplication.Creator {
    private val kodein = Kodein {
        /* bindings */
    }.direct
    override fun myActivity() = kodein.newInstance { MyActivity.Deps(instance(), instance()) }
}

----


