= Kodein DI on TornadoFX
Romain BOISSELLE <romain@boisselle.dev>
:toc: left
:toc-position: left
:toclevels: 5

:version: 6.2.0
:branch: 6.2

You can use Kodein as-is in your TornadoFX project, but you can level-up your game by using the libraries `kodein-di-framework-tornadofx-core`.

NOTE: Kodein does work on TornadoFX as-is.
      The `kodein-di-framework-tornadofx-core` extensions add multiple TornadoFX-specific utilities to Kodein. +
      Using or not using this extension really depends on your needs.

Have a look at the https://github.com/Kodein-Framework/Kodein-DI/tree/{branch}/demo/demo-tornadofx[TornadoFX demo project] to help you going further!


[[install]]
== Install

.How to quickly get into `kodein-di-framework-tornadofx-core`:
. Add this line in your `dependencies` block in your application `build.gradle` file:
+
[subs="attributes"]
.Gradle Groovy script
----
implementation 'org.kodein.di:kodein-di-generic-jvm:{version}'
implementation 'kodein-di-framework-tornadofx-core:{version}'
----
+
[subs="attributes"]
.Gradle Kotlin script
----
implementation("org.kodein.di:kodein-di-generic-jvm:{version}")
implementation("kodein-di-framework-tornadofx-core:{version}")
----
+
IMPORTANT: either `kodein-di-generic-jvm` or `kodein-di-erased` *must* be declared in addition to the `kodein-di-framework-tornadofx-core` package.
+
. Declare your `App` as `KodeinAware` and implement a `Kodein` container
+
[source, kotlin]
.Example: a TornadoFX Application declaration, `KodeinAware`, using TornadoFX DI as external source
----
class TornadoApplication : App(MainView::class), KodeinAware { <1>
    override val kodein: Kodein get() = Kodein { <2>
        extend(tornadoFXExternalSource) <3>
     } 
}
----
<1> Setting the `App` as `KodeinAware` will help you define a global `Kodein` container
<2> Define a `Kodein` container, accessible from almost anywhere in your application
<3> Branch `Kodein` upon `TornadoFX` dependency injection, to be able to access those dependencies through your `Kodein` container (see link:tornadofx.adoc#external-source[documentation])

WARNING: In order to leverage the power of `Kodein` and the helpers we made, you should really consider making your `App` as `KodeinAware`.

[[retrieving]]
== Retrieving

[[closest-kodein]]
=== Closest `Kodein` pattern

[[closest-tfx]]
==== From a `TornadoFX` perspective

[[closest-jfx]]
==== From a `JavaFX` perspective

[[kodein-extension]]
== Extension of `Kodein`

This section will cover how we can extend the use of `Kodein` in a `TornadoFX` application, like:

- Getting control of dependency injection over `TornadoFX`

- Defining specific `Kodein` containers in a `TornadoFX / JavaFX`'s graph

- Overriding a parent `Kodein` container in a `TornadoFX` component / `JavaFX` node

[[external-source]]
=== Using TornadoFX Dependency Injection as external source

[[kodein-containers]]
=== Specific `Kodein` containers

[[sub-kodein]]
=== `SubKodein`

[[scopes]]
== TornadoFX scopes