package org.kodein.di.generic

import org.kodein.di.*
import org.kodein.di.bindings.*
import org.kodein.type.TypeToken
import org.kodein.type.generic

@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("scoped<C>(scope)", "org.kodein.di"))
inline fun <reified C : Any> DI.Builder.scoped(scope: Scope<C>): DI.BindBuilder.WithScope<C> = DI.BindBuilder.WithScope.Impl(org.kodein.type.generic(), scope)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("contexted<C>()", "org.kodein.di"))
inline fun <reified C : Any> DI.Builder.contexted(): DI.BindBuilder.WithContext<C> = DI.BindBuilder.WithContext.Impl(org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("factory<C, A, T>(creator)", "org.kodein.di"))
inline fun <C : Any, reified A : Any, reified T: Any> DI.BindBuilder.WithContext<C>.factory(noinline creator: BindingDI<C>.(A) -> T) = Factory<C, A, T>(contextType, org.kodein.type.generic(), org.kodein.type.generic(), creator)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<C, T>(creator)", "org.kodein.di"))
inline fun <C : Any, reified T: Any> DI.BindBuilder.WithContext<C>.provider(noinline creator: NoArgBindingDI<C>.() -> T) = Provider(contextType, org.kodein.type.generic(), creator)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("singleton<C, T>(ref, sync, creator)", "org.kodein.di"))
inline fun <C : Any, reified T: Any> DI.BindBuilder.WithScope<C>.singleton(ref: RefMaker? = null, sync: Boolean = true, noinline creator: NoArgSimpleBindingDI<C>.() -> T) = Singleton(scope, contextType, org.kodein.type.generic(), ref, sync, creator)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("multiton<C, A, T>(ref, sync, creator)", "org.kodein.di"))
inline fun <C : Any, reified A : Any, reified T: Any> DI.BindBuilder.WithScope<C>.multiton(ref: RefMaker? = null, sync: Boolean = true, noinline creator: SimpleBindingDI<C>.(A) -> T) = Multiton<C, A, T>(scope, contextType, org.kodein.type.generic(), org.kodein.type.generic(), ref, sync, creator)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("eagerSingleton<T>(creator)", "org.kodein.di"))
inline fun <reified T: Any> DI.Builder.eagerSingleton(noinline creator: NoArgSimpleBindingDI<Any>.() -> T) = EagerSingleton(containerBuilder, generic(), creator)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<T>(instance)", "org.kodein.di"))
inline fun <reified T: Any> DI.Builder.instance(instance: T) = InstanceBinding(generic(), instance)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("bind<T>(tag, overrides)", "org.kodein.di"))
inline fun <reified T : Any> DI.Builder.bind(tag: Any? = null, overrides: Boolean? = null) = Bind<T>(org.kodein.type.generic(), tag, overrides)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("bind(tag, overrides)", "org.kodein.di"))
fun DI.Builder.bind(tag: Any? = null, overrides: Boolean? = null) = Bind(tag, overrides)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("with<T>(value)", "org.kodein.di"))
inline infix fun <reified T: Any> DI.Builder.ConstantBinder.with(value: T) = With(generic(), value)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("binding<T>(tag)", "org.kodein.di"))
inline fun <reified T: Any> SearchDSL.binding(tag: Any? = null) = SearchDSL.Binding(org.kodein.type.generic<T>(), tag)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("context<T>()", "org.kodein.di"))
inline fun <reified T : Any> SearchDSL.context() = Context(org.kodein.type.generic<T>())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("argument<T>()", "org.kodein.di"))
inline fun <reified T : Any> SearchDSL.argument() = Argument(org.kodein.type.generic<T>())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("factory<A, T>()", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.factory() = Factory<A, T>(org.kodein.type.generic(), org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("factoryOrNull<A, T>()", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.factoryOrNull() = FactoryOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<T>()", "org.kodein.di"))
inline fun <reified T : Any> Named.provider() = Provider<T>(org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<A, T>(arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.provider(arg: A) = Provider<A, T>(org.kodein.type.generic(), org.kodein.type.generic()) { arg }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<A, T>(arg)", "org.kodein.di"))
inline fun <A, reified T : Any> Named.provider(arg: Typed<A>) = Provider<A, T>(arg.type, org.kodein.type.generic()) { arg.value }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<A, T>(fArg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.provider(noinline fArg: () -> A) = Provider<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), fArg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<T>()", "org.kodein.di"))
inline fun <reified T : Any> Named.providerOrNull() = ProviderOrNull<T>(org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<A, T>(arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.providerOrNull(arg: A) = ProviderOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), { arg })
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<A, T>(arg)", "org.kodein.di"))
inline fun <A, reified T : Any> Named.providerOrNull(arg: Typed<A>) = ProviderOrNull<A, T>(arg.type, org.kodein.type.generic(), { arg.value })
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<A, T>(fArg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.providerOrNull(noinline fArg: () -> A) = ProviderOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), fArg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<T>()", "org.kodein.di"))
inline fun <reified T : Any> Named.instance() = Instance<T>(org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<A, T>(arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.instance(arg: A) = Instance<A, T>(org.kodein.type.generic(), org.kodein.type.generic()) { arg }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<A, T>(arg)", "org.kodein.di"))
inline fun <A, reified T : Any> Named.instance(arg: Typed<A>) = Instance<A, T>(arg.type, org.kodein.type.generic()) { arg.value }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<A, T>(fArg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.instance(noinline fArg: () -> A) = Instance<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), fArg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instanceOrNull<T>()", "org.kodein.di"))
inline fun <reified T : Any> Named.instanceOrNull() = InstanceOrNull<T>(org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instanceOrNull<A, T>(arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.instanceOrNull(arg: A) = InstanceOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic()) { arg }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instanceOrNull<A, T>(arg)", "org.kodein.di"))
inline fun <A, reified T : Any> Named.instanceOrNull(arg: Typed<A>) = InstanceOrNull<A, T>(arg.type, org.kodein.type.generic()) { arg.value }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instanceOrNull<A, T>(fArg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> Named.instanceOrNull(noinline fArg: () -> A) = InstanceOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), fArg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("constant<T>()", "org.kodein.di"))
inline fun <reified T : Any> DIAware.constant() = Constant<T>(org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("contextTranslator<C, S>(t)", "org.kodein.di"))
inline fun <reified C : Any, reified S : Any> contextTranslator(noinline t: (C) -> S): ContextTranslator<C, S> = SimpleContextTranslator(org.kodein.type.generic(), org.kodein.type.generic(), t)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("registerContextTranslator<C, S>(t)", "org.kodein.di"))
inline fun <reified C : Any, reified S : Any> DI.Builder.registerContextTranslator(noinline t: (C) -> S) = RegisterContextTranslator(org.kodein.di.contextTranslator(t))
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("contextFinder<S>(t)", "org.kodein.di"))
inline fun <reified S : Any> contextFinder(noinline t: () -> S) : ContextTranslator<Any, S> = SimpleAutoContextTranslator(org.kodein.type.generic(), t)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("registerContextFinder<S>(t)", "org.kodein.di"))
inline fun <reified S : Any> DI.Builder.registerContextFinder(noinline t: () -> S) = RegisterContextTranslator(org.kodein.di.contextFinder(t))
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("setBinding<T>()", "org.kodein.di"))
inline fun <reified T: Any> DI.Builder.setBinding() = SetBinding(TypeToken.Any, org.kodein.type.generic<T>(), org.kodein.type.generic<Set<T>>())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("argSetBinding<A, T>()", "org.kodein.di"))
inline fun <reified A : Any, reified T: Any> DI.Builder.argSetBinding() = ArgSetBinding(TypeToken.Any, org.kodein.type.generic<A>(), org.kodein.type.generic<T>(), org.kodein.type.generic<Set<T>>())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("inSet<T>()", "org.kodein.di"))
inline fun <reified T: Any> DI.Builder.TypeBinder<T>.inSet() = InSet(org.kodein.type.generic())
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("factoryOrNull<A, T>(tag)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> DirectDIAware.factoryOrNull(tag: Any? = null) = directDI.FactoryOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), tag)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<T>(tag)", "org.kodein.di"))
inline fun <reified T : Any> DirectDIAware.provider(tag: Any? = null) = directDI.Provider<T>(org.kodein.type.generic(), tag)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<A, T>(tag, arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> DirectDIAware.provider(tag: Any? = null, arg: A) = directDI.Factory<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), tag).toProvider { arg }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<A, T>(tag, arg)", "org.kodein.di"))
inline fun <A, reified T : Any> DirectDIAware.provider(tag: Any? = null, arg: Typed<A>) = directDI.Factory<A, T>(arg.type, org.kodein.type.generic(), tag).toProvider { arg.value }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("provider<A, T>(tag, fArg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> DirectDIAware.provider(tag: Any? = null, noinline fArg: () -> A) = directDI.Factory<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), tag).toProvider(fArg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<T>(tag)", "org.kodein.di"))
inline fun <reified T : Any> DirectDIAware.providerOrNull(tag: Any? = null) = directDI.ProviderOrNull<T>(org.kodein.type.generic(), tag)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<A, T>(tag, arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> DirectDIAware.providerOrNull(tag: Any? = null, arg: A) = directDI.FactoryOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), tag)?.toProvider { arg }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<A, T>(tag, arg)", "org.kodein.di"))
inline fun <A, reified T : Any> DirectDIAware.providerOrNull(tag: Any? = null, arg: Typed<A>) = directDI.FactoryOrNull<A, T>(arg.type, org.kodein.type.generic(), tag)?.toProvider { arg.value }
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("providerOrNull<A, T>(tag, fArg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> DirectDIAware.providerOrNull(tag: Any? = null, noinline fArg: () -> A) = directDI.FactoryOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), tag)?.toProvider(fArg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<T>(tag)", "org.kodein.di"))
inline fun <reified T : Any> DirectDIAware.instance(tag: Any? = null) = directDI.Instance<T>(org.kodein.type.generic(), tag)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<A, T>(tag, arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> DirectDIAware.instance(tag: Any? = null, arg: A) = directDI.Factory<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), tag).invoke(arg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instance<A, T>(tag, arg)", "org.kodein.di"))
inline fun <A, reified T : Any> DirectDIAware.instance(tag: Any? = null, arg: Typed<A>) = directDI.Factory<A, T>(arg.type, org.kodein.type.generic(), tag).invoke(arg.value)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instanceOrNull<T>(tag)", "org.kodein.di"))
inline fun <reified T : Any> DirectDIAware.instanceOrNull(tag: Any? = null) = directDI.InstanceOrNull<T>(org.kodein.type.generic(), tag)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instanceOrNull<A, T>(tag, arg)", "org.kodein.di"))
inline fun <reified A : Any, reified T : Any> DirectDIAware.instanceOrNull(tag: Any? = null, arg: A) = directDI.FactoryOrNull<A, T>(org.kodein.type.generic(), org.kodein.type.generic(), tag)?.invoke(arg)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("instanceOrNull<A, T>(tag, arg)", "org.kodein.di"))
inline fun <A, reified T : Any> DirectDIAware.instanceOrNull(tag: Any? = null, arg: Typed<A>) = directDI.FactoryOrNull<A, T>(arg.type, org.kodein.type.generic(), tag)?.invoke(arg.value)
@Deprecated(DEPRECATED_ERASED_GENERIC_7X, ReplaceWith("on<C>(context)", "org.kodein.di"))
inline fun <reified C : Any> DirectDIAware.on(context: C) = directDI.On(diContext(context))
