:version: 7.2.0
:branch: 7.2

[[install]]
= Install

[[install-jvm]]
== JVM

=== With Gradle

Add the JCenter repository:

[source,groovy,subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }
}
----

Then add the dependency:

[source,groovy,subs="attributes"]
----
dependencies {
    implementation 'org.kodein.di:kodein-di:{version}'
}
----

[TIP]
====
If you are *NOT* using *Gradle 6+*, you should declare the use of the Gradle Metadata experimental feature

[subs="attributes"]
.settings.gradle.kts
----
enableFeaturePreview("GRADLE_METADATA")
----

Or, import the JVM binaries with `implementation("org.kodein.di:kodein-di-jvm:{version}")`.
====

=== With Maven

Add the JCenter repository:

[source,xml,subs="attributes"]
----
&lt;repositories&gt;
    &lt;repository&gt;
      &lt;id&gt;jcenter&lt;/id&gt;
      &lt;url&gt;https://jcenter.bintray.com&lt;/url&gt;
    &lt;/repository&gt;
&lt;/repositories&gt;
----

Then add the dependency:

[source,xml,subs="attributes"]
----
&lt;dependencies&gt;
    &lt;dependency&gt;
        &lt;groupId&gt;org.kodein.di&lt;/groupId&gt;
        &lt;artifactId&gt;kodein-di-jvm&lt;/artifactId&gt;
        &lt;version&gt;{version}&lt;/version&gt;
    &lt;/dependency&gt;
&lt;/dependencies&gt;
----

WARNING: Use `kodein-di-jvm`, as _Kotlin/Multiplatform_ projects does not work with Maven

[[kotlin-multiplatform]]
== Kotlin/Multiplatform (Gradle)

NOTE: _Kodein-DI_ supports the following targets: +
androidArm32, androidArm64, iosArm32, iosArm64, iosX64, linuxArm32Hfp, linuxMips32, linuxMipsel32, linuxX64, macosX64, mingwX64

_Kodein-DI_ uses the new gradle native dependency model.

[TIP]
====
If you are *NOT* using *Gradle 6+*, you must declare the use of the Gralde Metadata experimental feature

[subs="attributes"]
.settings.gradle.kts
----
enableFeaturePreview("GRADLE_METADATA")
----

====

Add the JCenter repository:

[source,groovy,subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }
}
----

Then add the dependency:

[source,groovy,subs="attributes"]
----
kotlin {
    sourceSets {
        commonMain {
            dependencies {
                implementation "org.kodein.di:kodein-di:{version}"
            }
        }
    }
}
----

[[kotlin-js]]
== JavaScript (Gradle)

Because _Kodein-DI_ for JavaScript is compiled as a https://github.com/umdjs/umd[UMD module], it can be imported:

* In a browser:
** as an AMD module (for example with RequireJS) (See index.html in the demo project).
** Directly in an HTML page with a `<script>` tag (See index2.html in the demo project).
* In NodeJS, as a regular CJS module.

Add the JCenter repository:

[source,groovy,subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }
}
----

Then add the dependency:

[source,groovy,subs="attributes"]
----
dependencies {
    compile 'org.kodein.di:kodein-di-js:{version}'
}
----